backend1/backend1_djangoproject/django-Bank-project/bankproject/bankapp/urls.py
from django.urls import path,include
from . import views

urlpatterns = [

    path('',views.index,name='index'),
    path('login/',views.login,name='login'),
    path('register/', views.register, name='register'),
    path('logout',views.logout,name="logout"),
    path('create', views.create, name="create"),
    path('2/', views.all, name="all"),
    path('5/', views.tr, name="tr"),
    path('1', views.er, name="er"),
    path('3', views.th, name="th"),
    path('4', views.ko, name="ko"),

]

backend1/backend1_djangoproject/django-Bank-project/bankproject/bankproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from bankproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankapp.urls')),
    path('form/',include('formapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend1/backend1_djangoproject/django-Bank-project/bankproject/formapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.inde, name='inde'),
    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX

]

backend1/backend1_djangoproject/django-Bank-project/bankproject/formapp/models.py
from django.db import models

class District(models.Model):
    name=models.CharField(max_length=250)

    def __str__(self):
        return self.name

class Branch(models.Model):
    district=models.ForeignKey(District, on_delete=models.CASCADE)
    name=models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Person(models.Model):
    # name = models.CharField(max_length=124)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name

backend1/backend1_djangoproject/django-Bank-project/bankproject/formapp/forms.py
from django import forms
from formapp.models import District,Branch,Person

class demo_form(forms.ModelForm):

        class Meta:
                model = Person
                fields = '__all__'

        def __init__(self, *args, **kwargs):
                super().__init__(*args, **kwargs)
                self.fields['branch'].queryset = Branch.objects.none()

                if 'district' in self.data:
                        try:
                           district_id=int(self.data.get('district'))
                           self.fields['branch'].queryset=Branch.objects.filter(district_id=district_id).order_by('name')
                        except (ValueError, TypeError):
                                pass  # invalid input from the client; ignore and fallback to empty City queryset

                elif self.instance.pk:
                        self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

backend1/backend1_djangoproject/django-Bank-project/bankproject/bankapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib import messages, auth
from django.contrib.auth.models import User

from formapp.forms import demo_form

# Create your views here.

def index(request):
     # return HttpResponse("hello world")
    return render(request,"index.html")

def register(request):

        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            cpassword = request.POST['cpassword']
            if password == cpassword:
                if User.objects.filter(username=username).exists():
                    messages.info(request, "username taken")
                    return redirect('register')
                else:
                    user = User.objects.create_user(username=username,password=password, )
                    user.save();
                    # print("user created")
                    return redirect('login')

            else:
                messages.info(request, "password not matching")
                return redirect('register2')

            # return redirect('/')
        return render(request,"register2.html")
def login(request):
    if request.method =='POST':
        username=request.POST['username']
        password=request.POST['password']
        user=auth.authenticate(username=username,password=password)

        if user is not None:
         auth.login(request,user)
         return redirect('/')
        else:
          messages.info(request,"invalid user")
        return redirect('login2')
    return render(request,"login2.html")

def logout(request):
    auth.logout(request)
    return redirect('/')

def create(request):
    if request.method =='POST':

        messages.info(request, "application accepted")

    return render(request,"create.html")

def er(request):
    return render(request,"aer.html")
def ko(request):
    return render(request,"ako.html")

def th(request):
    return render(request,"ath.html")

def all(request):
    return render(request,"aal.html")

def tr(request):
    return render(request,"atr.html")

backend1/backend1_djangoproject/django-Bank-project/bankproject/formapp/views.py
from django.shortcuts import render
from.forms import demo_form
from .models import Person,District,Branch
from django.contrib import messages, auth

# Create your views here.
def inde(request):

    form = demo_form()
    # form=demo_form(request.POST)
    if request.method =='POST':
        messages.info(request, "Application accepted")


    return render(request,'demo1.html',{'form':form})

def load_cities(request):
    district_id = request.GET.get('district_id')
    cities = Branch.objects.filter(district_id=district_id).all()
    return render(request, 'city_dropdown_list_options.html', {'cities': cities})

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/aal.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Alappuzha</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<style>
        table,th,td{
        align:center;
         width:50%;
         border:1px solid black;
         border-collapse:collapse;
         text-align:center;
         }
</style>

</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
       <b>Fed bank</b>
      </a>
    </nav>
    <h1 align="center"> Alappuzha Branch Details</h1>

    <table align="center">
    <tr>
        <th >branch name</th>
        <th>alappuzha</th>
    </tr>
    <tr>
        <td>region</td>
        <td>kerala</td>
    </tr>
    <tr>
        <td>pincode</td>
        <td>688003</td>
    </tr>
        <tr>
        <td>phone</td>
        <td>0477-8738994 </td>
    </tr>
        <tr>
        <td>branch code</td>
        <td>7678</td>
    </tr>
        <tr>
        <td>ifsc code</td>
        <td>fed8292049</td>
    </tr>
</table>













</body>
</html>

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/aer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ernakulam</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<style>
        table,th,td{
        align:center;
         width:50%;
         border:1px solid black;
         border-collapse:collapse;
         text-align:center;
         }
</style>

</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
       <b>Fed bank</b>
      </a>
    </nav>
    <h1 align="center"> Ernakulam Branch Details</h1>

    <table align="center">
    <tr>
        <th >branch name</th>
        <th>Ernaklam</th>
    </tr>
    <tr>
        <td>region</td>
        <td>kochi</td>
    </tr>
    <tr>
        <td>pincode</td>
        <td>688004</td>
    </tr>
        <tr>
        <td>phone</td>
        <td>0477-8738994 </td>
    </tr>
        <tr>
        <td>branch code</td>
        <td>7678</td>
    </tr>
        <tr>
        <td>ifsc code</td>
        <td>fed8292049</td>
    </tr>
</table>













</body>
</html>

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/ako.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Kottayam</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<style>
        table,th,td{
        align:center;
         width:50%;
         border:1px solid black;
         border-collapse:collapse;
         text-align:center;
         }
</style>

</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
        <b>Fed bank</b>
      </a>
    </nav>
    <h1 align="center"> Kollam Branch Details</h1>

    <table align="center">
    <tr>
        <th >branch name</th>
        <th>Kollam</th>
    </tr>
    <tr>
        <td>region</td>
        <td>kerala</td>
    </tr>
    <tr>
        <td>pincode</td>
        <td>688004</td>
    </tr>
        <tr>
        <td>phone</td>
        <td>0477-8738994 </td>
    </tr>
        <tr>
        <td>branch code</td>
        <td>7678</td>
    </tr>
        <tr>
        <td>ifsc code</td>
        <td>fed8292049</td>
    </tr>
</table>













</body>
</html>

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/ath.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Thrissur</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<style>
        table,th,td{
        align:center;
         width:50%;
         border:1px solid black;
         border-collapse:collapse;
         text-align:center;
         }
</style>

</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
     <b>Fed bank</b>
      </a>
    </nav>
    <h1 align="center">  Thrissur Branch Details</h1>

    <table align="center">
    <tr>
        <th >branch name</th>
        <th>Thrissur</th>
    </tr>
    <tr>
        <td>region</td>
        <td>Kerala</td>
    </tr>
    <tr>
        <td>pincode</td>
        <td>688004</td>
    </tr>
        <tr>
        <td>phone</td>
        <td>0477-8738994 </td>
    </tr>
        <tr>
        <td>branch code</td>
        <td>7678</td>
    </tr>
        <tr>
        <td>ifsc code</td>
        <td>fed8292049</td>
    </tr>
</table>













</body>
</html>

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/atr.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Trivandrum</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<style>

        table,th,td{
        align:center;
         width:50%;
         border:1px solid black;
         border-collapse:collapse;
         text-align:center;
         }
</style>
</head>
<body>
<!-- Image and text -->
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="/">
    <b>Fed bank</b>
      </a>
    </nav>
    <h1 align="center"> Trivandrum Branch Details</h1>

    <table align="center">
    <tr>
        <th >branch name</th>
        <th>Trivandrum</th>
    </tr>
    <tr>
        <td>region</td>
        <td>Kerala</td>
    </tr>
    <tr>
        <td>pincode</td>
        <td>688004</td>
    </tr>
        <tr>
        <td>phone</td>
        <td>0477-8738994 </td>
    </tr>
        <tr>
        <td>branch code</td>
        <td>7678</td>
    </tr>
        <tr>
        <td>ifsc code</td>
        <td>fed8292049</td>
    </tr>
</table>
</body>
</html>

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}

backend1/backend1_djangoproject/django-Bank-project/bankproject/templates/demo1.html
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Account Form</title>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


        <link rel="stylesheet" href="https://codepen.io/gymratpacks/pen/VKzBEp#0">
        <link href='https://fonts.googleapis.com/css?family=Nunito:400,300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/main.css">
        <style>

        *, *:before, *:after {
  -moz-box-sizing: border-box;
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  bg-color:'green';
  font-family: 'Nunito', sans-serif;
  color: #384047;
}

form {
  max-width: 300px;
  margin: 10px auto;
  padding: 10px 20px;
  background: #f4f7f8;
  border-radius: 8px;
}

h1 {
  margin: 0 0 30px 0;
  text-align: center;
}

input[type="text"],
input[type="password"],
input[type="date"],
input[type="datetime"],
input[type="email"],
input[type="number"],
input[type="search"],
input[type="tel"],
input[type="time"],
input[type="url"],
textarea,
select {
  background: rgba(255,255,255,0.1);
  border: none;
  font-size: 16px;
  height: auto;
  margin: 0;
  outline: 0;
  padding: 15px;
  width: 100%;
  background-color: #e8eeef;
  color: #8a97a0;
  box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
  margin-bottom: 30px;
}

input[type="radio"],
input[type="checkbox"] {
  margin: 0 4px 8px 0;
}

select {
  padding: 6px;
  height: 32px;
  border-radius: 2px;
}

button {
  padding: 19px 39px 18px 39px;
  color: #FFF;
  background-color: #4bc970;
  font-size: 18px;
  text-align: center;
  font-style: normal;
  border-radius: 5px;
  width: 100%;
  border: 1px solid #3ac162;
  border-width: 1px 1px 3px;
  box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
  margin-bottom: 10px;
}

fieldset {
  margin-bottom: 30px;
  border: none;
}

legend {
  font-size: 1.4em;
  margin-bottom: 10px;
}

label {
  display: block;
  margin-bottom: 8px;
}

label.light {
  font-weight: 300;
  display: inline;
}

.number {
  background-color: #5fcf80;
  color: #fff;
  height: 30px;
  width: 30px;
  display: inline-block;
  font-size: 0.8em;
  margin-right: 4px;
  line-height: 30px;
  text-align: center;
  text-shadow: 0 1px 0 rgba(255,255,255,0.2);
  border-radius: 100%;
}

@media screen and (min-width: 480px) {

  form {
    max-width: 480px;
  }

}
h5{
text-align:center;
}

      </style>
    </head>
    <body bgcolor="yellow">

    <nav class="navbar navbar-expand-lg navbar-dark "style="background-color: black;">
        <a class="navbar-brand" href="/"><b>Fed bank</b></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}
          <li class="nav-item active">

              <a class="nav-link" href="{% url 'logout' %}">Logout <span class="sr-only">(current)</span></a>
          </li>
             {% endif %}
        </ul>
      </div>
    </nav>



{% for msg in messages %}
<h5>
    {{msg}}
    <p align="center"><a href="/">home</a></p>

</h5>
{% endfor %}

      <div class="row">
    <div class="col-md-12">
<!--      <form action="index.html" method="post">-->
          <form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
              {% csrf_token %}


        <h1> Account Form</h1>

        <fieldset>

<!--          <legend><span class="number">1</span> Your Basic Info</legend>-->

          <label>Name:</label>
          <input type="text" id="name" name="user_name" placeholder="Name" required>

          <label>Email:</label>
          <input type="email" id="mail" name="user_email" placeholder="Email" required>

          <label>Adress:</label>
          <input type="text" id="password"  name="user_password" placeholder="Address" required>

          <label>Age:</label>
                <input type="number" name="age" required placeholder="age"><br>
            <label>DOB:</label>
                <input type="date" name="DOB" required placeholder="age"><br>

            <label>Gender:</label>
          <input type="radio" id="under_13" value="under_13" name="user_age"><label for="under_13" class="light">male</label><br>
          <input type="radio" id="over_13" value="over_13" name="user_age"><label for="over_13" class="light">female</label>

        </fieldset>
        <fieldset>

<!--          <legend><span class="number">2</span> Your Profile</legend>-->

<!--         <label for="bio">Bio:</label>-->
<!--          <textarea id="bio" name="user_bio"></textarea>-->



         <label>Account Type:</label>
          <select id="job" name="user_job">
<!--            <optgroup label="Web">-->
              <option value="frontend_developer">savings account</option>
              <option value="php_developer">Current account</option>
<!--              <option value="python_developer">Python Developer</option>-->
<!--              <option value="rails_developer">Rails Developer</option>-->
<!--              <option value="web_designer">Web Designer</option>-->
<!--              <option value="wordpress_developer">Wordpress Developer</option>-->
<!--            </optgroup>-->
<!--            <optgroup label="Mobile">-->
<!--              <option value="android_developer">Android Developer</option>-->
<!--              <option value="ios_developer">IOS Developer</option>-->
<!--              <option value="mobile_designer">Mobile Designer</option>-->
<!--            </optgroup>-->
<!--            <optgroup label="Business">-->
<!--              <option value="business_owner">Business Owner</option>-->
<!--              <option value="freelancer">Freelancer</option>-->
<!--            </optgroup>-->
          </select>
          {{ form.as_p }}
          <label>Materials provide:</label>
          <input type="checkbox" id="development" value="interest_development" name="user_interest"><label class="light" for="development">Passbook</label><br>
          <input type="checkbox" id="design" value="interest_design" name="user_interest"><label class="light" for="design">Debit card</label><br>
          <input type="checkbox" id="business" value="interest_business" name="user_interest"><label class="light" for="business">Credit card</label>

         </fieldset>

        <button type="submit">submit application</button>

       </form>
        </div>
      </div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (branch) {
                    html_data += `<option value="${banch.id}">${branch.name}</option>`
                });
                console.log(html_data);
                $("#id_branch").html(html_data);

                */
            }
        });

    });
</script>
    </body>
</html>